# Generated by Django 4.0.3 on 2022-12-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.TextField()),
                ('sub_album_name', models.TextField()),
                ('image', models.TextField()),
                ('name', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery_album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.TextField()),
                ('banner_heading', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery_sub_album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.TextField()),
                ('sub_album_name', models.TextField()),
                ('sub_album_image', models.TextField()),
                ('sub_album_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery_youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='jeeyars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('prefix', models.TextField()),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('jeeyar_no_suffix', models.TextField()),
                ('image', models.TextField()),
                ('jeeyar_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='landing_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True)),
                ('h1', models.CharField(blank=True, max_length=2000)),
                ('h2', models.CharField(blank=True, max_length=2000)),
                ('p', models.CharField(blank=True, max_length=2000)),
                ('img', models.TextField(blank=True)),
                ('read_link', models.TextField(blank=True)),
                ('yt_link', models.TextField(blank=True)),
                ('file_link', models.TextField(blank=True)),
                ('yt_title', models.CharField(blank=True, max_length=2000)),
                ('file_title', models.CharField(blank=True, max_length=2000)),
                ('layout', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ponnadikkal_jeeyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='thaniyans_and_vazhi_thirunamams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vanamamalai_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vanamamalai_mutt_branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vanamamalai_other_temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vanamamalai_temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.TextField()),
                ('banner_heading', models.TextField()),
                ('content_title', models.TextField()),
                ('content_subtitle', models.TextField()),
                ('content_image', models.TextField()),
                ('tab1_heading', models.TextField()),
                ('tab1_desc', models.TextField()),
                ('tab1_schema', models.TextField()),
                ('tab2_heading', models.TextField()),
                ('tab2_desc', models.TextField()),
                ('tab2_schema', models.TextField()),
                ('tab3_heading', models.TextField()),
                ('tab3_desc', models.TextField()),
                ('tab3_schema', models.TextField()),
                ('tab4_heading', models.TextField()),
                ('tab4_desc', models.TextField()),
                ('tab4_schema', models.TextField()),
            ],
        ),
    ]
