# Generated by Django 4.0.3 on 2022-12-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jeeyars',
        ),
    ]
