# Generated by Django 4.0.3 on 2022-12-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_delete_jeeyars'),
    ]

    operations = [
        migrations.CreateModel(
            name='jeeyars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('prefix', models.TextField()),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('jeeyar_no_suffix', models.TextField()),
                ('image', models.TextField()),
                ('jeeyar_no', models.IntegerField()),
            ],
        ),
    ]
