# Generated by Django 4.0.3 on 2022-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_jeeyars'),
    ]

    operations = [
        migrations.CreateModel(
            name='vanamamalai_temple_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_id', models.IntegerField()),
                ('tab_heading', models.TextField()),
                ('tab_desc', models.TextField()),
                ('tab_schema', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab1_desc',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab1_heading',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab1_schema',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab2_desc',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab2_heading',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab2_schema',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab3_desc',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab3_heading',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab3_schema',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab4_desc',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab4_heading',
        ),
        migrations.RemoveField(
            model_name='vanamamalai_temple',
            name='tab4_schema',
        ),
    ]
