# Generated by Django 4.0.3 on 2022-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_vanamamalai_other_temple_tab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jeeyars_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeeyar_id', models.IntegerField()),
                ('tab_heading', models.TextField()),
                ('tab_desc', models.TextField()),
            ],
        ),
    ]
