# Generated by Django 4.0.3 on 2022-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_vanamamalai_mutt_branches_tab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ponnadikkal_jeeyar_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField()),
                ('tab_heading', models.TextField()),
                ('tab_desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ponnadikkal_jeeyar',
            name='banner_heading',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponnadikkal_jeeyar',
            name='banner_image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponnadikkal_jeeyar',
            name='content_image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponnadikkal_jeeyar',
            name='content_subtitle',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponnadikkal_jeeyar',
            name='content_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
