# Generated by Django 4.0.3 on 2022-12-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0010_ponnadikkal_jeeyar_tab_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponnadikkal_jeeyar_tab',
            old_name='branch_id',
            new_name='jeeyar_id',
        ),
    ]
