# Generated by Django 4.0.3 on 2022-12-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_rename_branch_id_ponnadikkal_jeeyar_tab_jeeyar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='vanamamalai_education_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeeyar_id', models.IntegerField()),
                ('tab_heading', models.TextField()),
                ('tab_desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vanamamalai_education',
            name='banner_heading',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanamamalai_education',
            name='banner_image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanamamalai_education',
            name='content_image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanamamalai_education',
            name='content_subtitle',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vanamamalai_education',
            name='content_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
