# Generated by Django 4.0.3 on 2022-12-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0015_landing_page_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_page',
            name='show_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
