# Generated by Django 4.0.3 on 2022-12-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0016_landing_page_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanamamalai_temple',
            name='banner_heading',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanamamalai_temple',
            name='banner_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanamamalai_temple',
            name='content_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanamamalai_temple',
            name='content_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanamamalai_temple',
            name='content_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanamamalai_temple_tab',
            name='tab_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanamamalai_temple_tab',
            name='tab_heading',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanamamalai_temple_tab',
            name='temple_id',
            field=models.IntegerField(blank=True),
        ),
    ]
