# Generated by Django 4.0.3 on 2022-12-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0018_ponnadikkal_jeeyar_show_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanamamalai_temple_tab',
            name='show_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
