# Generated by Django 4.0.3 on 2022-12-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0023_ponnadikkal_jeeyar_tab_show_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeeyars',
            name='show_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeeyars_tab',
            name='show_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
