# Generated by Django 4.0.3 on 2023-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0024_jeeyars_show_status_jeeyars_tab_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeeyars',
            name='banner_heading',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='banner_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='end_date',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='jeeyar_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='jeeyar_no_suffix',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='prefix',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='show_status',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='start_date',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars_tab',
            name='jeeyar_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars_tab',
            name='tab_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeeyars_tab',
            name='tab_heading',
            field=models.TextField(blank=True),
        ),
    ]
