# Generated by Django 4.0.3 on 2023-01-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0026_alter_jeeyars_jeeyar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_album',
            name='show_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jeeyars',
            name='show_status',
            field=models.BooleanField(),
        ),
    ]
