# Generated by Django 4.0.3 on 2023-01-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0027_gallery_album_show_status_alter_jeeyars_show_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='album_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='sub_album_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery_sub_album',
            name='album_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
