# Generated by Django 4.0.3 on 2023-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0029_delete_gallery_sub_album_remove_gallery_album_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootpagestatus',
            name='show_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
