# Generated by Django 4.0.3 on 2023-01-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0030_rootpagestatus_show_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootpagestatus',
            name='status',
        ),
    ]
