# Generated by Django 4.0.3 on 2023-01-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0031_remove_rootpagestatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True)),
                ('p', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('section_id', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='card_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='facebook_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='hero_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.TextField(blank=True)),
                ('h2', models.TextField(blank=True)),
                ('img', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='landing_page_flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_layout', models.TextField(blank=True)),
                ('show_status', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='small_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.TextField(blank=True)),
                ('h2', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('section_id', models.TextField(blank=True)),
            ],
        ),
    ]
