# Generated by Django 4.0.3 on 2023-01-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0032_banner_section_card_section_facebook_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_section',
            name='h1',
            field=models.TextField(blank=True),
        ),
    ]
