# Generated by Django 4.0.3 on 2023-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0033_banner_section_h1'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_section',
            name='h1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card_section',
            name='p',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card_section',
            name='section_id',
            field=models.TextField(blank=True),
        ),
    ]
