# Generated by Django 4.0.3 on 2023-01-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0036_suscribemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscribemodel',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suscribemodel',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suscribemodel',
            name='state',
            field=models.TextField(blank=True),
        ),
    ]
