# Generated by Django 4.0.3 on 2023-04-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0038_shishyaform'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeeyars',
            name='link_status',
            field=models.BooleanField(default=False),
        ),
    ]
